# Generated by Django 3.0.3 on 2020-03-02 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200227_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='dashboard',
            new_name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
